### ISSUE TITLE
模型准确率为何没有作者 2015 年的论文中准确率高?

### ISSUE THREAD

**Issue by zhaoerchao** [FudanNLP/adversarial-multi-criteria-learning-for-CWS#1]
作者曾在 2015 年发表论文 Long Short-Term Memory Neural Networks for Chinese Word Segmentation, 论文中使用 LSTM 模型进行中文分词, 在数据集 PKU/MSRA 上的准确率要高于本篇论文, 请问是什么原因?

**Comment by itortoise** [comment]
@zhaoerchao 请问你复现了这篇论文的实验了吗

**Comment by zhaoerchao** [comment]
我没有复现它的效果, 但做了基线测试

**Comment by itortoise** [comment]
@zhaoerchao 可否留一下联系方式，我有关于LSTM+CRF训练数据格式的问题想向你请教一下

**Comment by zhaoerchao** [comment]
@itortoise 邮箱: ec_zhao@126.com

**Comment by benben18** [comment]
> 我没有复现它的效果，但做了基线测试

请问你知道论文的数据格式是什么样子的吗？
